---
title: The Conquest of Ireland
creator:
- role: author
  text: Gerald of Wales
- role: translator
  text: Tomas Forester
- role: editor
  text: Thomas Wright
tags: [ireland, normans, england, wales]
abstract: |
  Gerald of Wales (1146-1223), bishop of noble extraction, in his
  histories, left an account of the Norman invasion and conquest of
  Ireland.

  The Irish conquest was an extension of the conquest of Wales--an
  activity of Norman lords in the marches who were acting more or less
  independently of the crown.
lang: en-US
rights: Public domain
publisher: AG
date: 2019-10-26
---
